[13.0] [MIG] website_oca_psc_team: Migration to v13.0
OCA/oca-custom pull request #45
Opened 2020-06-25 08:05 UTC by CarlosRoca13

cc @Tecnativa TT23216

2020-06-25 08:07 UTC, CarlosRoca13 commented
Please @pedrobaeza @ernestotejeda review this

2020-06-25 11:24 UTC, pedrobaeza requested changes

2020-06-25 11:24 UTC, pedrobaeza commented on website_oca_psc_team/templates/psc_category_template.xml
> +                         if project.image_256 else 'website_oca_psc_team/static/src/img/icon.png'"
`image_medium` was previously `128x128 image` and you unify the calls to the same field, caching it. At the end, all of them are resized at client (browser) level due to `height` and `width` attributes, and all occurrences are lower than 128x128.
```suggestion
                        t-att-src="'data:image/png;base64,%s'%to_text(project.image_128)
                         if project.image_128 else 'website_oca_psc_team/static/src/img/icon.png'"
```

2020-06-26 07:12 UTC, CarlosRoca13 commented
@pedrobaeza change done!

2020-06-26 07:32 UTC, pedrobaeza approved these changes

2020-07-03 14:03 UTC, pedrobaeza commented
/ocabot merge nobump

2020-07-03 14:19 UTC, merged