[14.0][MIG] oca_custom: Migration to 14.0
OCA/oca-custom pull request #50
Opened 2021-07-20 15:35 UTC by ernestotejeda

Cc @Tecnativa TT30003

Depends on:
  - [ ] github_connector: https://github.com/OCA/interface-github/pull/73

2021-07-21 06:08 UTC, victoralmau approved these changes

2021-07-21 06:14 UTC, joao-p-marques requested changes
Code review

2021-07-21 06:14 UTC, joao-p-marques commented on oca_custom/README.rst
> +* Make the github_login field from connector_github editable so it can be set
This is already done by the module, right? Can this point be removed?

2021-07-21 06:14 UTC, joao-p-marques commented on oca_custom/models/res_partner.py
> +    github_login = fields.Char(readonly=False)
This field was changed in the refactor to v14. Now it is called `github_name`. IMHO, that makes more sense, as it is a field shared across all github related models, and is not always a “login”. I have done migration scripts in the refactor, so you would just need to change this to:
```suggestion
    github_name = fields.Char(readonly=False)
```

2021-07-28 21:16 UTC, ernestotejeda commented
@joao-p-marques changes done

2021-07-29 05:18 UTC, CarlosRoca13 approved these changes

2021-07-29 05:37 UTC, joao-p-marques approved these changes

2021-07-29 06:11 UTC, pedrobaeza commented
/ocabot merge nobump

2021-07-29 06:17 UTC, merged